language: elixir
elixir:
  - "1.7"
  - "1.8"
otp_release:
  - 20.0
  - 21.0
script:
  - "MIX_ENV=test mix local.hex --force"
  - "mix credo --ignore readability --strict"
  - "MIX_ENV=test mix do deps.get, test"
