name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - name: Install Deps
        run: mix deps.get
      - name: Lint
        run: |
          mix format --check-formatted
          mix credo --ignore readability --strict
      - name: Test
        run: mix test --cover
        env:
          MIX_ENV: test